title: I might be an alcoholic
email: jaroslav.sladek@gmail.com
description: An engine that creates more stats based on your untappd-data
baseurl: "/"

# Build settings
permalink: pretty
encoding: UTF-8

collections:
  monthly:
    output: true
